version: '3.5'

services:
  spring:
    container_name: spring
    image: gorani-spring:prod
    environment:
      - SECRET=${SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
  
  db:
    container_name: db
    image: gorani-db:prod
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
